name: CI

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  test:
    lint: true
    uses: fastify/workflows/.github/workflows/plugins-ci.yml@v3
